FROM node:22

WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy package configs
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/app/package.json packages/app/
COPY packages/web/package.json packages/web/
COPY packages/shared/package.json packages/shared/

# Install deps
RUN pnpm install --frozen-lockfile

# Copy source
COPY . .

# Build web and app
RUN pnpm run --filter shared build \
    && pnpm run --filter web build \
    && pnpm run --filter app build

ENV NODE_ENV=production
EXPOSE 3000

# Run hono server
WORKDIR /app/packages/web
CMD ["pnpm", "start"]
