# Use Node.js 22 as the base image
FROM node:22

# Set the working directory in the container
WORKDIR /app

# Enable Corepack to manage package managers like pnpm
RUN corepack enable \
  && corepack prepare pnpm@latest --activate

# Copy over the root configuration files
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

# copy all package.json
COPY packages/bootstrap/package.json packages/bootstrap/
COPY packages/proxy/package.json packages/proxy/
COPY packages/shared/package.json packages/shared/
COPY packages/web/package.json packages/web/

# Install dependencies using pnpm
RUN pnpm install

# Copy the rest of the application code
COPY . .

# build
RUN pnpm run --filter shared build \
  && pnpm run --filter web build

ENV NODE_ENV=production
EXPOSE 3000
WORKDIR /app/packages/web
CMD ["pnpm", "start"]
